apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secret
  namespace: sonarqube
type: Opaque
data:
  postgres-username: c29uYXJ1c2Vy  # base64 encoded value of "sonaruser"
  postgres-password: c29uYXJwYXNz  # base64 encoded value of "sonarpass"
  postgres-database: c29uYXJkYg==  # base64 encoded value of "sonardb"
  postgres-host: cG9zdGdyZXNxbC5zZXJ2aWNlLm5hbWVzcGFjZQ==  # base64 encoded value of "postgresql.service.namespace"
