kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: sonarqube
  name: pv0001
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql/
