apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: devops
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db