apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  namespace: devops
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: "gp2"
  resources:
    requests:
      storage: 1Gi