apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    role: frontend
  type: LoadBalancer